#!/usr/bin/env bash
# Repo-wide style gate: no em dashes and no tool-attribution phrases in any
# tracked file. Run over the whole tree in CI as a merge-time backstop.
#
# Portable: BSD-compatible grep, bash 3.2 (macOS) and bash 4+ (CI).

set -u

FAIL=0

# Em dash U+2014, built via printf so this script contains no em-dash byte.
EMDASH=$(printf '\xe2\x80\x94')

# This script legitimately contains the forbidden phrases (to detect them), so
# exclude it from the phrase scan.
is_enforcement_file() {
  case "$1" in
    scripts/check-style.sh) return 0 ;;
    *) return 1 ;;
  esac
}

# Third-party test-fixture DATA (real-world specs vendored verbatim) is not
# authored prose, so it is exempt from the em-dash and attribution scans.
is_exempt_file() {
  case "$1" in
    */Fixtures/*) return 0 ;;
    *) return 1 ;;
  esac
}

# Tool-attribution phrases. Assembled from fragments so this script does not
# contain the full literal phrases (which would self-flag in other scanners).
TOOL="Cla""ude"
PHRASES=(
  "Co-Authored-By: $TOOL"
  "Co-authored-by: $TOOL"
  "Generated with $TOOL"
  "Generated by $TOOL"
  "Powered by $TOOL"
  "as an AI"
)

while IFS= read -r f; do
  [ -f "$f" ] || continue
  is_exempt_file "$f" && continue
  if LC_ALL=C grep -qF -- "$EMDASH" "$f" 2>/dev/null; then
    echo "style: em dash (U+2014) in $f" >&2
    FAIL=1
  fi
  if ! is_enforcement_file "$f"; then
    for p in "${PHRASES[@]}"; do
      if LC_ALL=C grep -qF -- "$p" "$f" 2>/dev/null; then
        echo "style: forbidden attribution phrase in $f" >&2
        FAIL=1
      fi
    done
  fi
done < <(git ls-files)

if [ "$FAIL" -ne 0 ]; then
  echo "style: gate failed (no em dashes, no tool attribution)." >&2
fi
exit "$FAIL"
